name: Build a weabpp and deploy
on:
  push:
      branches:
        - main


jobs:
  Build_and_deploy:
      name: build and deploy
      runs-on: ubuntu-runner

      steps:

           - name: Checkout the code
             uses: actions/checkout@v3

           - name: Install Node.js
             uses: actions/setup-node@v3
             with:
                node-version: '20.x'

           - name: Install Dependencies
             run: npm install

           - name: Build webapp
             run: npm run build

           - name: Deploy to Azure App Service
             uses: azure@webapp-deploy@v3
             with:
              app-name: 'my-webapp-000'
              slot-name: 'staging'
              publish-profile:  ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          

    
