name: Azure Webapp Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
   runs-on: ubuntu-latest

   steps:
  
     - name: Checkout the code
       uses: actions/checkout@v3

     - name: Setup node.js
       uses: actions/setup-node@v3
       with:
          node-version: '16'

     - name: Install Dependencies
       run:  npm install

     - name: Deploy to azure web app
       uses:  azure/webapps-deploy@v3
       with:
          app-name: my-webapp-000
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          package: .
            
              

    
